apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: collector
    namespace: default # Assuming Argo CD is installed in the default namespace, adjust if it's in a different namespace like argocd
spec:
    project: default
    source:
        repoURL: https://github.com/celian-hamon/bloc-3-indiv.git
        targetRevision: main
        path: k8s
    destination:
        server: https://kubernetes.default.svc
        namespace: collector
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
